var name=prompt("Enter your name");
var email=prompt("Enter your Email");
var pass=prompt("Enter your Password");
var age=prompt("Enter your age");
var flag=confirm("Continue?");
console.log("Your personal details :");
console.log("Your name is :",name);
console.log("Your Email is :",email);
console.log("Your Password is :",pass);
console.log("Your age is :",age);
//var no1=prompt("Enter First Number"); whatever data comes in promt it will be string,so have to convert
var no1=Number(prompt("Enter First Number"));
var no2=Number(prompt("Enter Second Number"));
var exp;
console.log("First number is :",no1);
console.log("Second number is :",no2);
alert("Addition");
exp=no1+no2;
console.log("Addition of these number :",exp);
alert("Subtraction");
exp=no2-no1;
console.log("Subtraction of these number :",exp);
alert("Multiplication");
exp=no2*no1;
console.log("Multiplication of these number :",exp);
alert("Division");
exp=no2/no1;
console.log("Division of these number :",exp);
exp=no1*no1;
alert("Square");
console.log("Square of First number :",exp);
alert("Cube");
exp=no1*no1*no1;
console.log("Cube of First number :",exp);
